from django import forms
from .models import *

class IbanForm(forms.Form):
    phone = forms.CharField(max_length = 100)
    name = forms.CharField(max_length = 100)


class CrearPropiedadForma(forms.Form):
    oferta = forms.CharField(max_length = 30)
    tipo = forms.CharField(max_length = 30)
    titulo = forms.CharField(max_length = 200)
    desc = forms.CharField()
    habs = forms.IntegerField(required=False)
    banos = forms.FloatField(required=False)
    garaje = forms.IntegerField(required=False)
    pais = forms.CharField(max_length = 100)
    estado = forms.CharField(max_length = 100)
    codigo_postal = forms.CharField(max_length = 5)
    colonia = forms.CharField(max_length = 200)
    direccion = forms.CharField(max_length = 300)
    precio = forms.CharField(max_length = 100)
    negociable = forms.BooleanField(widget=forms.CheckboxInput(), required=False)
    dif = forms.CharField(max_length = 100, required=False)
    m_terr = forms.CharField(max_length = 30)
    m_cons = forms.CharField(max_length = 30)
    pisos = forms.IntegerField(required=False)
    portada = forms.ImageField(widget=forms.ClearableFileInput())
    # extra = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    video = forms.CharField(max_length = 150, required=False)

class EditarPropiedadForma(forms.Form):
    oferta = forms.CharField(max_length = 30)
    tipo = forms.CharField(max_length = 30)
    titulo = forms.CharField(max_length = 200)
    desc = forms.CharField()
    habs = forms.IntegerField(required=False)
    banos = forms.FloatField(required=False)
    garaje = forms.IntegerField(required=False)
    pais = forms.CharField(max_length = 100)
    estado = forms.CharField(max_length = 100)
    codigo_postal = forms.CharField(max_length = 5)
    colonia = forms.CharField(max_length = 200)
    direccion = forms.CharField(max_length = 300)
    precio = forms.CharField(max_length = 100)
    negociable = forms.BooleanField(widget=forms.CheckboxInput(), required=False)
    dif = forms.CharField(max_length = 100, required=False)
    m_terr = forms.CharField(max_length = 30)
    m_cons = forms.CharField(max_length = 30)
    pisos = forms.IntegerField(required=False)
    portada = forms.ImageField(widget=forms.ClearableFileInput(), required=False)
    extra = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)
    video = forms.CharField(max_length = 150, required=False)
